[general]
import = [
    "~/.config/alacritty/themes/nord.toml"
]

[window]
# padding.y = 0
# padding.x = 0
padding.y = 7
padding.x = 7
opacity = 0.8

[font]
# size = 10.6
size = 10

[font.normal]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.bold]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.italic]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"
style = "Italic"

[font.bold_italic]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"
